version: '3.9'
services:
  bikeramp:
    container_name: bikeramp-api-dev
    command: npm run start:debug
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
