FROM node:16-alpine3.16
WORKDIR /app
COPY ["nest-cli.json", "package.json", "package-lock.json", "tsconfig.json", "tsconfig.build.json", ".eslintrc.js", "./"]
RUN npm install

FROM base as init
COPY src/ ./src
COPY test/ ./test

FROM init as tests
RUN npm run lint
RUN npm run test

FROM tests as build-prod
RUN npm run build
RUN npm-ci --omit-dev
RUN rm -rf test/
RUN rm -rf src/
CMD ["npm", "run", "start:prod"]
