version: '3.9'
services:
  bikeramp:
    container_name: bikeramp-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    depends_on:
      - postgres
    env_file:
      - .env
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine3.16
    container_name: bikeramp_database
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - bikeramp_vol:/var/lib/postgresql/data

volumes:
  bikeramp_vol:
    name: bikeramp_vol
